// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace projetinho.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205210551_AjusteModelo")]
    partial class AjusteModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinhaApi.Models.LoteMinerio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalizacaoAtual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinaOrigem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("P")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SiO2")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TeorFe")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Toneladas")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Umidade")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("LotesMinerio");
                });
#pragma warning restore 612, 618
        }
    }
}
