version: '3.8'

services:
  minhaapi:
    build: .
    container_name: minhaapi
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      Redis__ConnectionString: "redis:6379"
      DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB:-minhaapi_db};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres}"
    networks:
      - minhaapi_network

  postgres:
    image: postgres:16
    container_name: pg_estudos
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-minhaapi_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - pgdata_estudos:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-minhaapi_db}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - minhaapi_network

  redis:
    image: redis:latest
    container_name: redis_estudos
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - minhaapi_network

volumes:
  pgdata_estudos:
    driver: local

networks:
  minhaapi_network:
    driver: bridge
